// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum ScreenshotShieldMessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class ScreenshotShieldMessagesPigeonCodecReader: FlutterStandardReader {
}

private class ScreenshotShieldMessagesPigeonCodecWriter: FlutterStandardWriter {
}

private class ScreenshotShieldMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ScreenshotShieldMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ScreenshotShieldMessagesPigeonCodecWriter(data: data)
  }
}

class ScreenshotShieldMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ScreenshotShieldMessagesPigeonCodec(readerWriter: ScreenshotShieldMessagesPigeonCodecReaderWriter())
}

var screenshotShieldMessagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: ScreenshotShieldMessagesPigeonCodecReaderWriter());

/// Calls made from Dart into the host platform.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ScreenshotShieldHostApi {
  func startListening() throws
  func stopListening() throws
  func setProtected(protected: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ScreenshotShieldHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ScreenshotShieldMessagesPigeonCodec.shared }
  /// Sets up an instance of `ScreenshotShieldHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ScreenshotShieldHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startListeningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.screenshot_shield.ScreenshotShieldHostApi.startListening\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startListeningChannel.setMessageHandler { _, reply in
        do {
          try api.startListening()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startListeningChannel.setMessageHandler(nil)
    }
    let stopListeningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.screenshot_shield.ScreenshotShieldHostApi.stopListening\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopListeningChannel.setMessageHandler { _, reply in
        do {
          try api.stopListening()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopListeningChannel.setMessageHandler(nil)
    }
    let setProtectedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.screenshot_shield.ScreenshotShieldHostApi.setProtected\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setProtectedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let protectedArg = args[0] as! Bool
        do {
          try api.setProtected(protected: protectedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setProtectedChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// Events emitted from the host platform into Dart.
class OnScreenshotDetectedStreamHandler: PigeonEventChannelWrapper<Int64> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: OnScreenshotDetectedStreamHandler) {
    var channelName = "dev.flutter.pigeon.screenshot_shield.ScreenshotShieldEventChannelApi.onScreenshotDetected"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<Int64>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: screenshotShieldMessagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
