// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.ajibolaak.screenshot_guard

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ScreenshotGuardMessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class ScreenshotGuardMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

val ScreenshotGuardMessagesPigeonMethodCodec = StandardMethodCodec(ScreenshotGuardMessagesPigeonCodec())

/**
 * Calls made from Dart into the host platform.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ScreenshotGuardHostApi {
  fun startListening()
  fun stopListening()
  fun setProtected(protected: Boolean)

  companion object {
    /** The codec used by ScreenshotGuardHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ScreenshotGuardMessagesPigeonCodec()
    }
    /** Sets up an instance of `ScreenshotGuardHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ScreenshotGuardHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.screenshot_guard.ScreenshotGuardHostApi.startListening$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startListening()
              listOf(null)
            } catch (exception: Throwable) {
              ScreenshotGuardMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.screenshot_guard.ScreenshotGuardHostApi.stopListening$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopListening()
              listOf(null)
            } catch (exception: Throwable) {
              ScreenshotGuardMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.screenshot_guard.ScreenshotGuardHostApi.setProtected$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val protectedArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setProtected(protectedArg)
              listOf(null)
            } catch (exception: Throwable) {
              ScreenshotGuardMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class ScreenshotGuardMessagesPigeonStreamHandler<T>(
    val wrapper: ScreenshotGuardMessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface ScreenshotGuardMessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/** Events emitted from the host platform into Dart. */
abstract class OnScreenshotDetectedStreamHandler : ScreenshotGuardMessagesPigeonEventChannelWrapper<Long> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnScreenshotDetectedStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.screenshot_guard.ScreenshotGuardEventChannelApi.onScreenshotDetected"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = ScreenshotGuardMessagesPigeonStreamHandler<Long>(streamHandler)
      EventChannel(messenger, channelName, ScreenshotGuardMessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from ScreenshotGuardMessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<Long>) {}

override fun onCancel(p0: Any?) {}
}
      
